version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  ai-reader:
    build: .
    container_name: ai-reader
    ports:
      - "8501:8501"
    volumes:
      - ./app/docs:/app/docs
    depends_on:
      - ollama

volumes:
  ollama_data:
